version: '3.8'
services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: PGUSER
      POSTGRES_PASSWORD: PGPASS
    ports:
      - 5555:5432
    volumes:
      - monorepodata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6666:6379
    volumes:
      - redisdata:/data
  mongo:
    image: mongo
    restart: always
    ports:
      - 7777:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - monorepodata:/data/db
    
volumes:
  monorepodata:
    driver: local
  redisdata:
    driver: local
  mongodbdata:
    driver: local